import type { Business } from "./data";

/**
 * Seed v2 — usado APENAS como fallback se o Supabase estiver indisponível,
 * para o site nunca abrir em branco. A fonte da verdade é a tabela
 * public.comercios (ver lib/comercios.ts). Mantenha em sincronia com a
 * migration 20260612000000_comercios.sql.
 *
 * ~60 comércios realistas da Asa Sul e Asa Norte de Brasília.
 * ids no padrão `{quadra}{s|n}-{bloco}` (s=Sul, n=Norte).
 */
export const SEED_BUSINESSES: Business[] = [
  // ---------------- ASA SUL ----------------
  { id: "106s-a", nome: "Padaria Pão da Praça", categoria: "Padaria", asa: "Sul", quadra: 106, bloco: "A", capivaras: 4.5, avaliacoes: 142 },
  { id: "106s-b", nome: "Café do Pequi", categoria: "Cafeteria", asa: "Sul", quadra: 106, bloco: "B", capivaras: 4.8, avaliacoes: 233 },
  { id: "108s-a", nome: "Restaurante Cerrado Vivo", categoria: "Restaurante", asa: "Sul", quadra: 108, bloco: "A", capivaras: 4.6, avaliacoes: 318 },
  { id: "108s-c", nome: "Farmácia Asa Saudável", categoria: "Farmácia", asa: "Sul", quadra: 108, bloco: "C", capivaras: 4.1, avaliacoes: 64 },
  { id: "109s-b", nome: "Academia Movimento Brasília", categoria: "Academia", asa: "Sul", quadra: 109, bloco: "B", capivaras: 4.3, avaliacoes: 187 },
  { id: "109s-d", nome: "Sorveteria Geladinho do Lago", categoria: "Sorveteria", asa: "Sul", quadra: 109, bloco: "D", capivaras: 4.9, avaliacoes: 276 },
  { id: "110s-a", nome: "Barbearia Candango", categoria: "Barbearia", asa: "Sul", quadra: 110, bloco: "A", capivaras: 4.7, avaliacoes: 154 },
  { id: "110s-e", nome: "Pet Shop Mundo Animal", categoria: "Pet Shop", asa: "Sul", quadra: 110, bloco: "E", capivaras: 4.4, avaliacoes: 98 },
  { id: "112s-b", nome: "Pizzaria Forno do Plano", categoria: "Pizzaria", asa: "Sul", quadra: 112, bloco: "B", capivaras: 4.6, avaliacoes: 211 },
  { id: "112s-f", nome: "Lavanderia Roupa Limpa", categoria: "Lavanderia", asa: "Sul", quadra: 112, bloco: "F", capivaras: 4.0, avaliacoes: 37 },
  { id: "113s-c", nome: "Ótica Olhar do Cerrado", categoria: "Ótica", asa: "Sul", quadra: 113, bloco: "C", capivaras: 4.2, avaliacoes: 71 },
  { id: "114s-a", nome: "Mercado Quadra Viva", categoria: "Mercado", asa: "Sul", quadra: 114, bloco: "A", capivaras: 3.9, avaliacoes: 58 },
  { id: "114s-d", nome: "Salão Beleza do Cerrado", categoria: "Salão de Beleza", asa: "Sul", quadra: 114, bloco: "D", capivaras: 4.5, avaliacoes: 129 },
  { id: "116s-b", nome: "Clínica Bem-Estar Sul", categoria: "Clínica", asa: "Sul", quadra: 116, bloco: "B", capivaras: 4.4, avaliacoes: 92 },
  { id: "206s-a", nome: "Padaria Trigo de Ouro", categoria: "Padaria", asa: "Sul", quadra: 206, bloco: "A", capivaras: 4.3, avaliacoes: 88 },
  { id: "207s-c", nome: "Bar do Juscelino", categoria: "Bar", asa: "Sul", quadra: 207, bloco: "C", capivaras: 4.5, avaliacoes: 264 },
  { id: "208s-b", nome: "Estética Pele de Brasília", categoria: "Estética", asa: "Sul", quadra: 208, bloco: "B", capivaras: 4.6, avaliacoes: 103 },
  { id: "209s-a", nome: "Lanchonete Pão com Bolinho", categoria: "Lanchonete", asa: "Sul", quadra: 209, bloco: "A", capivaras: 4.1, avaliacoes: 76 },
  { id: "210s-d", nome: "Cafeteria Grão do Eixo", categoria: "Cafeteria", asa: "Sul", quadra: 210, bloco: "D", capivaras: 4.8, avaliacoes: 198 },
  { id: "211s-b", nome: "Farmácia Vida Plena", categoria: "Farmácia", asa: "Sul", quadra: 211, bloco: "B", capivaras: 4.0, avaliacoes: 49 },
  { id: "212s-a", nome: "Restaurante Tempero Mineiro", categoria: "Restaurante", asa: "Sul", quadra: 212, bloco: "A", capivaras: 4.7, avaliacoes: 341 },
  { id: "213s-e", nome: "Papelaria Risca e Rabisca", categoria: "Papelaria", asa: "Sul", quadra: 213, bloco: "E", capivaras: 4.2, avaliacoes: 44 },
  { id: "214s-c", nome: "Academia Corpo no Eixo", categoria: "Academia", asa: "Sul", quadra: 214, bloco: "C", capivaras: 4.4, avaliacoes: 226 },
  { id: "216s-a", nome: "Pizzaria Massa Boa", categoria: "Pizzaria", asa: "Sul", quadra: 216, bloco: "A", capivaras: 4.5, avaliacoes: 173 },
  { id: "306s-b", nome: "Sorveteria Açaí da Asa", categoria: "Sorveteria", asa: "Sul", quadra: 306, bloco: "B", capivaras: 4.9, avaliacoes: 287 },
  { id: "307s-a", nome: "Barbearia Navalha de Prata", categoria: "Barbearia", asa: "Sul", quadra: 307, bloco: "A", capivaras: 4.6, avaliacoes: 118 },
  { id: "308s-d", nome: "Pet Shop Patas Felizes", categoria: "Pet Shop", asa: "Sul", quadra: 308, bloco: "D", capivaras: 4.3, avaliacoes: 81 },
  { id: "309s-c", nome: "Mercado da Vizinhança", categoria: "Mercado", asa: "Sul", quadra: 309, bloco: "C", capivaras: 3.8, avaliacoes: 52 },
  { id: "310s-a", nome: "Clínica Sorriso do Plano", categoria: "Clínica", asa: "Sul", quadra: 310, bloco: "A", capivaras: 4.7, avaliacoes: 136 },
  { id: "312s-b", nome: "Ótica Visão Candanga", categoria: "Ótica", asa: "Sul", quadra: 312, bloco: "B", capivaras: 4.1, avaliacoes: 63 },
  { id: "313s-e", nome: "Estética Spa do Lago Sul", categoria: "Estética", asa: "Sul", quadra: 313, bloco: "E", capivaras: 4.8, avaliacoes: 149 },
  { id: "314s-a", nome: "Lanchonete X da Quadra", categoria: "Lanchonete", asa: "Sul", quadra: 314, bloco: "A", capivaras: 4.2, avaliacoes: 95 },
  { id: "316s-c", nome: "Lavanderia Express Sul", categoria: "Lavanderia", asa: "Sul", quadra: 316, bloco: "C", capivaras: 4.0, avaliacoes: 41 },
  { id: "409s-a", nome: "Padaria Pão & Companhia", categoria: "Padaria", asa: "Sul", quadra: 409, bloco: "A", capivaras: 4.6, avaliacoes: 132 },
  { id: "409s-d", nome: "Cafeteria Grão Especial", categoria: "Cafeteria", asa: "Sul", quadra: 409, bloco: "D", capivaras: 4.8, avaliacoes: 210 },
  { id: "409s-f", nome: "Barbearia do Téo", categoria: "Barbearia", asa: "Sul", quadra: 409, bloco: "F", capivaras: 4.9, avaliacoes: 156 },
  { id: "410s-a", nome: "Restaurante Sabor da Asa", categoria: "Restaurante", asa: "Sul", quadra: 410, bloco: "A", capivaras: 4.5, avaliacoes: 174 },
  { id: "410s-c", nome: "Salão Beleza Pura", categoria: "Salão de Beleza", asa: "Sul", quadra: 410, bloco: "C", capivaras: 4.3, avaliacoes: 73 },
  { id: "411s-a", nome: "Pizzaria Forno a Lenha", categoria: "Pizzaria", asa: "Sul", quadra: 411, bloco: "A", capivaras: 4.6, avaliacoes: 198 },
  { id: "411s-b", nome: "Bar do Zé", categoria: "Bar", asa: "Sul", quadra: 411, bloco: "B", capivaras: 4.1, avaliacoes: 64 },
  { id: "412s-e", nome: "Papelaria Caderno Aberto", categoria: "Papelaria", asa: "Sul", quadra: 412, bloco: "E", capivaras: 4.3, avaliacoes: 48 },
  { id: "504s-a", nome: "Mercado Central da 504", categoria: "Mercado", asa: "Sul", quadra: 504, bloco: "A", capivaras: 4.0, avaliacoes: 67 },
  { id: "508s-b", nome: "Academia Bluefit Sul", categoria: "Academia", asa: "Sul", quadra: 508, bloco: "B", capivaras: 4.4, avaliacoes: 312 },
  { id: "513s-a", nome: "Clínica Saúde Total", categoria: "Clínica", asa: "Sul", quadra: 513, bloco: "A", capivaras: 4.5, avaliacoes: 121 },
  { id: "513s-c", nome: "Sorveteria Açaí da 513", categoria: "Sorveteria", asa: "Sul", quadra: 513, bloco: "C", capivaras: 4.8, avaliacoes: 187 },
  { id: "516s-a", nome: "Farmácia Droga Plano", categoria: "Farmácia", asa: "Sul", quadra: 516, bloco: "A", capivaras: 4.2, avaliacoes: 58 },

  // ---------------- ASA NORTE ----------------
  { id: "106n-a", nome: "Café com Letras", categoria: "Cafeteria", asa: "Norte", quadra: 106, bloco: "A", capivaras: 4.9, avaliacoes: 245 },
  { id: "108n-c", nome: "Restaurante Cantinho Norte", categoria: "Restaurante", asa: "Norte", quadra: 108, bloco: "C", capivaras: 4.4, avaliacoes: 198 },
  { id: "109n-b", nome: "Padaria Trigo Dourado", categoria: "Padaria", asa: "Norte", quadra: 109, bloco: "B", capivaras: 4.3, avaliacoes: 96 },
  { id: "110n-a", nome: "Academia FitNorte", categoria: "Academia", asa: "Norte", quadra: 110, bloco: "A", capivaras: 4.1, avaliacoes: 143 },
  { id: "112n-d", nome: "Barbearia Navalha", categoria: "Barbearia", asa: "Norte", quadra: 112, bloco: "D", capivaras: 4.6, avaliacoes: 84 },
  { id: "113n-b", nome: "Pet Shop Patas & Cia", categoria: "Pet Shop", asa: "Norte", quadra: 113, bloco: "B", capivaras: 4.5, avaliacoes: 112 },
  { id: "206n-a", nome: "Pizzaria Bella Norte", categoria: "Pizzaria", asa: "Norte", quadra: 206, bloco: "A", capivaras: 4.5, avaliacoes: 167 },
  { id: "208n-c", nome: "Ótica Foco Norte", categoria: "Ótica", asa: "Norte", quadra: 208, bloco: "C", capivaras: 4.2, avaliacoes: 54 },
  { id: "210n-b", nome: "Bar da Esquina Norte", categoria: "Bar", asa: "Norte", quadra: 210, bloco: "B", capivaras: 4.4, avaliacoes: 231 },
  { id: "211n-a", nome: "Lavanderia Norte Limpa", categoria: "Lavanderia", asa: "Norte", quadra: 211, bloco: "A", capivaras: 3.9, avaliacoes: 38 },
  { id: "212n-e", nome: "Salão Studio Beleza Norte", categoria: "Salão de Beleza", asa: "Norte", quadra: 212, bloco: "E", capivaras: 4.6, avaliacoes: 124 },
  { id: "214n-b", nome: "Mercado Bom Preço Norte", categoria: "Mercado", asa: "Norte", quadra: 214, bloco: "B", capivaras: 4.0, avaliacoes: 73 },
  { id: "306n-a", nome: "Estética Renovar Norte", categoria: "Estética", asa: "Norte", quadra: 306, bloco: "A", capivaras: 4.7, avaliacoes: 108 },
  { id: "308n-c", nome: "Farmácia Norte Saúde", categoria: "Farmácia", asa: "Norte", quadra: 308, bloco: "C", capivaras: 4.1, avaliacoes: 61 },
  { id: "310n-b", nome: "Sorveteria Gela Norte", categoria: "Sorveteria", asa: "Norte", quadra: 310, bloco: "B", capivaras: 4.8, avaliacoes: 176 },
  { id: "312n-a", nome: "Lanchonete Burguer da Asa", categoria: "Lanchonete", asa: "Norte", quadra: 312, bloco: "A", capivaras: 4.3, avaliacoes: 142 },
  { id: "408n-a", nome: "Clínica Vida Norte", categoria: "Clínica", asa: "Norte", quadra: 408, bloco: "A", capivaras: 4.5, avaliacoes: 97 },
  { id: "408n-d", nome: "Papelaria Lápis e Cor", categoria: "Papelaria", asa: "Norte", quadra: 408, bloco: "D", capivaras: 4.2, avaliacoes: 39 },
  { id: "410n-b", nome: "Restaurante Prato Cheio Norte", categoria: "Restaurante", asa: "Norte", quadra: 410, bloco: "B", capivaras: 4.6, avaliacoes: 289 },
  { id: "412n-a", nome: "Cafeteria Norte do Café", categoria: "Cafeteria", asa: "Norte", quadra: 412, bloco: "A", capivaras: 4.7, avaliacoes: 161 },
  { id: "508n-c", nome: "Academia Power Norte", categoria: "Academia", asa: "Norte", quadra: 508, bloco: "C", capivaras: 4.4, avaliacoes: 254 },
  { id: "512n-b", nome: "Padaria Forno Norte", categoria: "Padaria", asa: "Norte", quadra: 512, bloco: "B", capivaras: 4.3, avaliacoes: 84 },
];
